# Misc
float32_matmul_precision : "medium" # Default is highest if you GPU doesn't have Tensor Cores 

# Network
batch_size : 64 
block_size : 256 # Maximum context length
dropout : 0.2
eval_interval : 300
head_size : 64
lr : 0.0003
max_epochs : 3_000
max_steps : -1 
n_embeddings : 384
n_heads : 6
n_layers : 6
